FROM mcr.microsoft.com/playwright:focal

WORKDIR /usr/src/app

COPY ./requirements.txt ./

RUN apt-get update && apt-get install python3 && apt-get install python3-pip

RUN pip install -r requirements.txt

RUN playwright install

RUN playwright install-deps

COPY . .

CMD ["python","-u","gmail_automation.py"]